## To Calculate reiman sum from left end approximation, right end approximation and mid point approximation method

## Instructions to use this code for calculating reimansum
        i_ First of all create a object of class named reiman_sum and pass three parameters first one is N then upper limit then
            lower limit.
        ii_ There are four method.
            (a)left_end_approx()    for left end approximation.
            (b)right_end_approx()   for right end approximation.
            (c)mid_point_approx()   for mid point approximation.
            (d)rsum(your fn here w.r.t "x")   for calculating area of all approximation.
        iii_ After creating object you have to choose desired approximation method and then run area method to calculate.

In [81]:
import numpy as np
class reiman_sum:
    def __init__(self,N,upper_limit,lower_limit):
        global delta_x
        self.N=N
        self.b=upper_limit
        self.a=lower_limit
        delta_x=(upper_limit-lower_limit)/ N
    def left_end_approx(self):
        global x
        x=[self.a]
        for i in range(self.N-1):
            element=x[i]+delta_x
            x.append(element)
        x=np.array(x)
        print(f"x={x}")
    def right_end_approx(self):
        global x
        x=[self.a+delta_x]
        for i in range(self.N-1):
            element=x[i]+delta_x
            x.append(element)
        x=np.array(x)
        print(f"x={x}")
    def mid_point_approx(self):
        global x
        mid_point=(self.a+delta_x)/2
        x=[mid_point]
        for i in range(self.N-1):
            element=x[i]+delta_x
            x.append(element)
        x=np.array(x)
        print(f"x={x}")
    def rsum(self,fx):
        self.fn=fx
        fn=np.array(fx)
        area=np.array(fn*delta_x)
        left_end_approximation=area.sum()
        print(f"The approximation with Reiman Sum is {left_end_approximation}")

#### Q1 : Calculate Reiman sum of N = 10, upper limit = 3 and lower limit = 0, given that the fn is 9-x^2

### Left end Approximation

In [82]:
#creating object N=10, upper limit is 3 and lower limit  is 0.
a=reiman_sum(10,3,0)

In [83]:
# Find the value of x which is actually interval points
a.left_end_approx()

x=[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7]


In [84]:
# Interval points are following with  step size 10 because N=10
x

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

In [85]:
# function value from the above values of x
9-x**2

array([9.  , 8.91, 8.64, 8.19, 7.56, 6.75, 5.76, 4.59, 3.24, 1.71])

In [86]:
# Find reiman sum with the help of rsum method
a.rsum(9-x**2)

The approximation with Reiman Sum is 19.305000000000003


### Right end approximation

In [87]:
#creating object N=10, upper limit is 3 and lower limit  is 0.
# you can also calculate all method with  single object but not suggested to do this.
b=reiman_sum(10,3,0)

In [88]:
# Find the value of x which is actually interval points
b.right_end_approx()

x=[0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7 3. ]


In [89]:
# function value from the above values of x
9-x**2

array([8.91000000e+00, 8.64000000e+00, 8.19000000e+00, 7.56000000e+00,
       6.75000000e+00, 5.76000000e+00, 4.59000000e+00, 3.24000000e+00,
       1.71000000e+00, 1.77635684e-15])

In [90]:
# Find reiman sum with the help of rsum method
b.rsum(9-x**2)

The approximation with Reiman Sum is 16.605


### Mid point approximation

In [91]:
#creating object N=10, upper limit is 3 and lower limit  0is
c=reiman_sum(10,3,0)

In [92]:
# Find the value of x which is actually interval points
c.mid_point_approx()

x=[0.15 0.45 0.75 1.05 1.35 1.65 1.95 2.25 2.55 2.85]


In [93]:
# function value from the above values of x
9-x**2

array([8.9775, 8.7975, 8.4375, 7.8975, 7.1775, 6.2775, 5.1975, 3.9375,
       2.4975, 0.8775])

In [95]:
# Find reiman sum with the help of rsum method
c.rsum(9-x**2)

The approximation with Reiman Sum is 18.0225
